CREATE TABLE "tipo_producto" (
  "id_tipo_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "colores" (
  "id_color" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "modelos" (
  "id_modelo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "tipo_movimiento" (
  "id_tipo_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "tipo_talla" (
  "id_tipo_talla" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "canales_venta" (
  "id_canal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "usuarios" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "rol" varchar(50) NOT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (current_timestamp),
  "ultima_acceso" timestamp
);

CREATE TABLE "tallas" (
  "id_talla" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" varchar(10) NOT NULL,
  "id_tipo_talla" int NOT NULL
);

CREATE TABLE "productos" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tipo_producto" int NOT NULL,
  "id_modelo" int NOT NULL,
  "id_color" int NOT NULL,
  "id_talla" int,
  "sku" varchar(50) UNIQUE NOT NULL,
  "stock_minimo" int DEFAULT 0,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "movimiento_stock" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "id_canal" int,
  "id_usuario" int NOT NULL,
  "id_tipo_movimiento" int NOT NULL,
  "cantidad" int NOT NULL,
  "observaciones" varchar(500),
  "fecha_movimiento" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "stock_madre" (
  "id_stock" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "cantidad_disponible" int NOT NULL DEFAULT 0,
  "ultima_actualizacion" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "notificaciones" (
  "id_notificacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "tipo" varchar(20) NOT NULL,
  "mensaje" varchar(500) NOT NULL,
  "leida" boolean DEFAULT false,
  "fecha_creacion" timestamp DEFAULT (current_timestamp)
);

ALTER TABLE "tallas" ADD FOREIGN KEY ("id_tipo_talla") REFERENCES "tipo_talla" ("id_tipo_talla");

ALTER TABLE "productos" ADD FOREIGN KEY ("id_tipo_producto") REFERENCES "tipo_producto" ("id_tipo_producto");

ALTER TABLE "productos" ADD FOREIGN KEY ("id_modelo") REFERENCES "modelos" ("id_modelo");

ALTER TABLE "productos" ADD FOREIGN KEY ("id_color") REFERENCES "colores" ("id_color");

ALTER TABLE "productos" ADD FOREIGN KEY ("id_talla") REFERENCES "tallas" ("id_talla");

ALTER TABLE "movimiento_stock" ADD FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto");

ALTER TABLE "movimiento_stock" ADD FOREIGN KEY ("id_canal") REFERENCES "canales_venta" ("id_canal");

ALTER TABLE "movimiento_stock" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario");

ALTER TABLE "movimiento_stock" ADD FOREIGN KEY ("id_tipo_movimiento") REFERENCES "tipo_movimiento" ("id_tipo_movimiento");

ALTER TABLE "stock_madre" ADD FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto");

ALTER TABLE "notificaciones" ADD FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto");
